name: phonologic
description: "A new Flutter project."
publish_to: 'none'
version: 0.1.0

environment:
  sdk: ^3.7.2

dependencies:
  flutter:
    sdk: flutter
  flutter_3d_controller: ^2.2.0
  flutter_tts: ^4.2.2
  google_fonts: ^6.2.1
  whiteboard: ^1.0.0
  sqflite: ^2.4.2
  flutter_launcher_icons: ^0.14.3


dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0

flutter:
  uses-material-design: true
  assets:
    - assets/lists/
#    - assets/audio/
    - assets/images/
    - assets/models/